### ISSUE TITLE
'libfreenect2/config.h' file not found

### ISSUE THREAD

**Issue by mimouncadosch** [giacomodabisias/libfreenect2pclgrabber#13]
Hi,

Thanks for writing this program, it's very helpful.

When running make, I am getting the following error:
```/usr/local/include/libfreenect2/include/libfreenect2/libfreenect2.hpp:32:10: fatal error: 'libfreenect2/config.h' file not found
#include <libfreenect2/config.h>```

This is my CMakeLists.txt file:

```

cmake_minimum_required(VERSION 2.8)
Project (Kinect2Grabber CXX)

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11") 
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")
set(CMAKE_BUILD_TYPE Release) 
set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/modules")

# http://derekmolloy.ie/hello-world-introductions-to-cmake/
set(FREENECT2_INCLUDE_DIRS "/usr/local/include/libfreenect2/include")
set(FREENECT2_LIBRARY "/usr/local/include/libfreenect2")

option(WITH_OPENCL "adds opencl support for freenect2" OFF)

find_package(OpenCV REQUIRED)
find_package(PCL 1.7 REQUIRED)
find_package(Freenect2 REQUIRED)

link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

include_directories(${OpenCV_INCLUDE_DIRS})
include_directories(${PCL_INCLUDE_DIRS})
include_directories(${FREENECT2_INCLUDE_DIRS})

add_executable(Kinect2Grabber test.cpp)

target_link_libraries(Kinect2Grabber ${OpenCV_LIBS} ${FREENECT2_LIBRARY} ${PCL_LIBRARIES})
```

What should I set my `FREENECT2_LIBRARY` to be?

Thanks

**Comment by giacomodabisias** [comment]
This is wrong I belive
set(FREENECT2_INCLUDE_DIRS "/usr/local/include/libfreenect2/include")
set(FREENECT2_LIBRARY "/usr/local/include/libfreenect2")

How did you install libfreenect2? with sudo make install?
In that case the library will be libfreenect2.so inside /usr/local/lib and the include should be /usr/local/include/libfreenect2
so try with the following
set(FREENECT2_INCLUDE_DIRS "/usr/local/include/libfreenect2")
set(FREENECT2_LIBRARY "/usr/local/lib")
Anyway it should not be necessary since There is the find package so you can re5move those lines if you have built freenect2 and then installed the libraries and include files.

**Comment by mimouncadosch** [comment]
Bingo!
You were right, I hadn't installed libfreenect2  with sudo. 

I re-installed it with sudo make install and the error went away.

Thanks again for the super prompt response

**Comment by giacomodabisias** [comment]
No problem,
have fun with it
